import { z } from 'zod';

export const orderImportDataSchema = z.object({
    id: z.string().optional(),
    serviceType: z.string().min(1),
    meterNumber: z.string().min(1),
    orderStatus: z.string().min(1),
    issueDate: z.string().min(1),
    issueTime: z.string().optional(),
    accountNumber: z.string().min(1),
    lastName: z.string().min(1),
    firstName: z.string().min(1),
    idNumber: z.string().min(1),
    email: z.string().min(1),
    phone: z.string().min(1),
    orderLocation: z.string().min(1),
    panelTowerBlock: z.string().optional(),
    coordinateX: z.number().optional(),
    coordinateY: z.number().optional(),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    appliedTariff: z.string().optional(),
    transformerNumber: z.string().optional(),
    distributionNetwork: z.string().optional(),
    transformerOwnership: z.string().optional(),
    sharedSubstation: z.string().optional(),
    normalLoad: z.string().optional(),
    fluctuatingLoad: z.string().optional(),
    plannerGroup: z.string().optional(),
    workPosition: z.string().optional(),
    lockerSequence: z.string().optional(),
    observations: z.string().optional(),
    technicianId: z.number().optional(),
});

export const orderSchema = z.object({
    id: z.string().min(1),
    technicianId: z.number().optional(),
    serviceType: z.string().min(1),
    meterNumber: z.string().min(1),
    status: z.string().min(1),
    issueDate: z.string().min(1),
    issueTime: z.string().optional(),
    accountNumber: z.string().min(1),
    lastName: z.string().min(1),
    firstName: z.string().min(1),
    idNumber: z.string().min(1),
    email: z.string().min(1),
    phone: z.string().min(1),
    orderLocation: z.string().min(1),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    observations: z.string().optional(),
    panelTowerBlock: z.string().optional(),
    coordinateX: z.number().optional(),
    coordinateY: z.number().optional(),
    appliedTariff: z.string().optional(),
    transformerNumber: z.string().optional(),
    distributionNetwork: z.string().optional(),
    transformerOwnership: z.string().optional(),
    sharedSubstation: z.string().optional(),
    normalLoad: z.string().optional(),
    fluctuatingLoad: z.string().optional(),
    plannerGroup: z.string().optional(),
    workPosition: z.string().optional(),
    lockerSequence: z.string().optional(),
});

export type OrderImportDataInput = z.infer<typeof orderImportDataSchema>;
export type OrderInput = z.infer<typeof orderSchema>;
